baseURL = "https://benobi.one/"
languageCode = "en-us"
title = "benobi.one"
theme = ["hugo-embed-pdf-shortcode", "hugo-coder-portfolio"]
enableInlineShortcodes = true

DefaultContentLanguage = "en"
googleAnalytics = "UA-162042800-1"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "benobi.one"
    description = "Ben Sigman - security, engineering, and product leadership."
    keywords = "blog,developer,personal"
    info = "Ben Sigman - security, engineering, and product leadership."
    avatarurl = "images/unicornvision.jpg"
    footercontent = "benobi.one"
    fixedbarContent = "Let's keep the internet safe and free? →→ "
    fixedbarContentAfter = "You're a generous Jedi."

    hideCredits = true
    hideCopyright = true

    # Bottom sns share
    snsShare = true
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false
    enableFacebookShare = false
    enableHatenaShare = false
    enableLineShare = false
    enableLinkedInShare = false
    enableenableEFFDonate = true

   thumbnail = "images/benobi-one.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bensig/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/bensig/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bensig/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 4
    url = "https://medium.com/@bensig/"
[[params.social]]
    name = "angel.co"
    icon = "fab fa-angellist"
    weight = 5
    url = "https://angel.co/bensig/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Benobi.one"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Ben Sigman"
            info = "Tech. Product. Business. Ethos."
            #            info = "Do or do not. There is no try."
            description = "innerspace, cyberspace, outerspace"
            keywords = "blog,developer,personal,ben sigman"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1
                url = "about"
            [[languages.en.menu.main]]
                name = "Blog"
                weight = 2
                url = "posts"
            [[languages.en.menu.main]]
                name = "Projects"
                weight = 3
                url = "projects"
            [[languages.en.menu.main]]
                name = "Advocacy"
                weight = 4
                url = "initiatives"
            [[languages.en.menu.main]]
                name = "Resources"
                weight = 5
                url = "resources"
            [[languages.en.menu.main]]
                name = "Contact"
                weight = 6
                url = "contact"
